
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED ';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS ';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_VACATION = 'GET_VACATION';
export const VACATION_ERROR = 'VACATION_ERROR';
export const GET_VACATION_BY_USER = 'GET_VACATION_BY_USER';
export const UPDATE_FOLLOW = 'UPDATE_FOLLOW';
export const DELETE_VACATION = 'DELETE_VACATION';
export const NEW_VACATION = 'NEW_VACATION';
export const EDIT_VACATION = 'EDIT_VACATION';
export const GET_VACATION_DATA = 'GET_VACATION_DATA';

